[toolchain]
anchor_version = "0.32.1"

[features]
seeds = true
skip-lint = false

[programs.devnet]
proof_of_futures = "J6CRBYD9b8vjZJsY61usKT986oAxxZMoGigzwkNHkdD4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/proof_of_futures"]
